Repository enjin/platform-beam, pull requests merged in 2023-11, with the labels that each got.

#43 Support null transaction wallet
  src/Commands/BatchProcess.php
Labels: enhancement

#44 Adds v1.0.0 to release
  .github/workflows/code_analysis.yml
  .github/workflows/run_tests.yml
  .github/workflows/security_checker.yml
  src/Commands/BatchProcess.php
Labels: dependencies

#45 Add attributes field
  lang/en/type.php
  src/GraphQL/Types/AttributeType.php
  src/GraphQL/Types/BeamClaimType.php
  tests/Feature/GraphQL/Resources/GetClaims.graphql
Labels: enhancement

#46 Add Attributes Field to BeamClaimType
  lang/en/type.php
  src/GraphQL/Types/AttributeType.php
  src/GraphQL/Types/BeamClaimType.php
  tests/Feature/GraphQL/Resources/GetClaims.graphql
Labels: enhancement

#48 Add get pending claims
  lang/en/query.php
  src/GraphQL/Queries/GetPendingClaimsQuery.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  tests/Feature/GraphQL/Queries/GetPendingClaimsTest.php
  tests/Feature/GraphQL/Resources/GetPendingClaims.graphql
Labels: enhancement

#54 [PLA-1440] Return empty object
  src/Support/ClaimProbabilities.php
Labels: bug

#53 [PLA-1445] Add logging for tracing errors
  src/Jobs/ClaimBeam.php
  src/Services/BeamService.php
Labels: enhancement

#52 [PLA-1431] Exclude attributes from pending claims query
  src/GraphQL/Types/BeamClaimType.php
Labels: enhancement

#55 [PLA-1449] Add transaction data
  src/GraphQL/Types/BeamClaimType.php
  src/Models/Laravel/BeamClaim.php
  src/Models/Laravel/Traits/EagerLoadSelectFields.php
  tests/Feature/GraphQL/Resources/GetClaims.graphql
  tests/Feature/GraphQL/Resources/GetPendingClaims.graphql
Labels: enhancement

#56 [PLA-1463] Add atomic locking
  .github/workflows/pr_agent.yml
  src/Enums/PlatformBeamCache.php
  src/Jobs/ClaimBeam.php
Labels: bug
