Repository enjin/platform-beam, pull requests merged in 2024-07, with the labels that each got.

#85 [PLA-1891] Hide sensitive attributes from beam APIs
  src/GraphQL/Queries/GetBeamsQuery.php
  src/GraphQL/Types/BeamType.php
  tests/Feature/GraphQL/Queries/GetBeamTest.php
  tests/Feature/GraphQL/Queries/GetBeamsTest.php
Labels: enhancement, Review effort [1-5]: 1

#87 [PLA-1899] Expose qr and code for get beam
  src/GraphQL/Types/BeamType.php
  tests/Feature/GraphQL/Queries/GetBeamTest.php
  tests/Feature/GraphQL/Queries/GetBeamsTest.php
Labels: enhancement, Review effort [1-5]: 1

#86 [PLA-1896] Fix validation create beam on mint on demand
  src/GraphQL/Mutations/CreateBeamMutation.php
  tests/Feature/GraphQL/Mutations/CreateBeamTest.php
Labels: bug, tests, Review effort [1-5]: 2, Bug fix

#88 [PLA-1907] Fixes Beam transactions
  composer.json
  src/Commands/BatchProcess.php
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#90 [PLA-1915] Fixes beams encoding
  src/Commands/BatchProcess.php
Labels: enhancement, Review effort [1-5]: 2, Bug fix
